name: ml-project
channels:
  - defaults
  - pytorch
  - fvcore
  - iopath
dependencies:
  - python=3.10

  - fvcore
  - iopath

  - flake8
  - mypy
  - black

  - pytorch=1.12
  - torchvision
  - scikit-learn
  - jupyterlab
  - matplotlib
  - pandas
  - pytest
  - seaborn
